[package]
name = "deno-paas-plugin"
version = "0.1.0"
authors = ["Tim Ermilov <yamalight@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
deno_core = "0.31.0"
